export interface PortfolioItem {
  id: string;
  name: string; // Project Title
  client?: string; // Client Name
  slug?: string;
  description: string; // Short Summary
  category?: string; // e.g. Web, App, Branding
  industry?: string; // e.g. Healthcare, Fintech
  services?: string[]; // Array of services provided
  timeline?: string; // e.g. 6 Months
  year?: string; // e.g. 2024
  techStack?: string[];
  
  // Hero Section
  heroImage?: string;
  intro?: string;
  duration?: string;

  // Overview Section
  scope?: string;
  platform?: string;
  deliverables?: string[];
  teamRole?: string;

  // Main Content
  challenge?: string;
  goal?: string;
  solution?: string;
  keyFeatures?: string[];
  designDirection?: string;
  outcome?: string;
  fullStory?: string; // Legacy field for flexibility

  // Visuals
  imageUrl: string; // Thumbnail/Cover
  galleryImages?: string[];
  mobileMockups?: string[];
  desktopMockups?: string[];
  videoUrl?: string;

  // Design System & Architecture
  uiComponents?: string[]; // UI/UX components used (e.g. "Radix Accordion", "Custom Chart")
  systemDiagram?: string; // URL to system architecture diagram
  systemDiagramCaption?: string;

  // Trust & Metadata
  testimonial?: {
    quote: string;
    author: string;
    role: string;
  };
  impact?: string;
  relatedProjectIds?: string[];
  url: string; // External Project Link

  // SEO & Display
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: string;
  isFeatured?: boolean;
  isVisibleOnHome?: boolean;
  status?: 'draft' | 'published';
  order?: number;
}

export const initialProjects: PortfolioItem[] = [
  {
    id: '1',
    name: 'BANCAT.ORG.BD',
    client: 'BANCAT Foundation',
    slug: 'bancat-foundation',
    description: 'A comprehensive digital platform for healthcare accessibility, donation management, and community support across Bangladesh.',
    category: 'Web',
    industry: 'Healthcare & Nonprofit',
    services: ['Web Design', 'Full-Stack Development', 'UX Research', 'Payment Integration'],
    timeline: '4 Months',
    year: '2024',
    techStack: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'PostgreSQL', 'SSLCommerz'],
    heroImage: 'https://images.unsplash.com/photo-1576091160550-217359f42f8c?auto=format&fit=crop&q=80&w=2670',
    intro: 'Empowering a healthcare nonprofit with a world-class digital presence and seamless donation infrastructure.',
    duration: '4 Months',
    scope: 'End-to-end web platform: public-facing site, donation portal, patient management, admin dashboard.',
    platform: 'Web (Responsive)',
    deliverables: ['Responsive Website', 'Donation Portal', 'Patient CMS', 'Admin Dashboard', 'SEO Optimization'],
    teamRole: 'Lead Design & Development Partner',
    challenge: 'BANCAT Foundation lacked a centralized digital hub. Patient data was scattered across spreadsheets, donations were handled manually via bank transfers, and their online presence was virtually nonexistent — crippling their ability to scale impact.',
    goal: 'Build an integrated platform that serves as the single source of truth for patient records, automates donation collection with local payment gateways, and tells the foundation\'s story in a compelling, trustworthy way.',
    solution: 'We designed and built a high-performance Next.js application with a secure SSLCommerz-powered donation portal, a Kanban-style patient management system for internal teams, and an SEO-optimized public site with dynamic content sections for stories and campaigns.',
    keyFeatures: [
      'Real-time donation tracking with SSLCommerz integration',
      'Patient record management with role-based access',
      'Dynamic "Inspiring Stories" section with CMS',
      'Campaign fundraising pages with progress bars',
      'Bilingual support (English & Bengali)',
      'Automated email receipts for donors'
    ],
    designDirection: 'Compassionate yet professional. The palette uses calming greens and blues to evoke trust, paired with bold typography for impact. Every interaction is designed to lower the barrier between a visitor and becoming a donor.',
    outcome: 'Within the first month of launch, online donations increased by 340%. The admin team reduced patient data entry time by 60%. The site now serves as the primary channel for all fundraising campaigns.',
    fullStory: 'BANCAT\'s mission required a design that was both compassionate and technically robust. We spent two weeks in discovery, interviewing staff and donors to understand the pain points. The result is a system that not only looks beautiful but fundamentally changed how the organization operates.',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-217359f42f8c?auto=format&fit=crop&q=80&w=2670',
    galleryImages: [
      'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&q=80&w=2670',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=2426',
      'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&q=80&w=2676',
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2670'
    ],
    mobileMockups: [],
    desktopMockups: [],
    videoUrl: '',
    uiComponents: ['Hero Banner with Parallax', 'Donation Progress Card', 'Patient Kanban Board', 'Campaign Timeline', 'Stats Counter Widget', 'Bilingual Toggle Switch'],
    systemDiagram: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'End-to-end architecture: Next.js frontend → REST API → PostgreSQL with SSLCommerz payment gateway integration',
    testimonial: {
      quote: 'QoArc didn\'t just build us a website — they gave us the infrastructure to save more lives. Our donation flow is seamless now.',
      author: 'Dr. Fariha Rahman',
      role: 'Director, BANCAT Foundation'
    },
    impact: '340% increase in online donations, 60% reduction in admin workload, 12,000+ unique visitors in the first quarter.',
    relatedProjectIds: ['3'],
    url: 'https://BANCAT.ORG.BD',
    metaTitle: 'BANCAT Foundation — Digital Healthcare Platform by QoArc',
    metaDescription: 'How QoArc built a comprehensive digital platform for BANCAT Foundation, integrating donation management, patient records, and a compelling public-facing site.',
    ogImage: 'https://images.unsplash.com/photo-1576091160550-217359f42f8c?auto=format&fit=crop&q=80&w=2670',
    isFeatured: true,
    isVisibleOnHome: true,
    status: 'published',
    order: 1
  },
  {
    id: '2',
    name: 'Vaultify — Fintech Super App',
    client: 'Vaultify Inc.',
    slug: 'vaultify-fintech-app',
    description: 'A next-generation mobile banking experience with AI-powered spending insights, biometric security, and peer-to-peer transfers.',
    category: 'App',
    industry: 'Fintech & Banking',
    services: ['Mobile App Design', 'React Native Development', 'API Architecture', 'Security Consulting'],
    timeline: '6 Months',
    year: '2024',
    techStack: ['React Native', 'Node.js', 'MongoDB', 'Stripe API', 'TensorFlow Lite', 'Firebase'],
    heroImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f2?auto=format&fit=crop&q=80&w=2670',
    intro: 'Redefining personal finance with an intelligent mobile-first banking experience that puts users in complete control.',
    duration: '6 Months',
    scope: 'Full product design and development from concept to App Store launch, including backend API infrastructure.',
    platform: 'iOS & Android (React Native)',
    deliverables: ['Native Mobile App', 'REST API Backend', 'Admin Portal', 'Analytics Dashboard', 'Security Audit Report'],
    teamRole: 'Product Design & Development Lead',
    challenge: 'Traditional banking apps in the region are clunky, slow, and offer zero insight into spending habits. Users under 30 were abandoning banking apps entirely, managing finances through fragmented chat-based transfers.',
    goal: 'Create a mobile banking experience so intuitive that it feels like a social app — fast, beautiful, and intelligent — while maintaining bank-grade security and compliance standards.',
    solution: 'We built Vaultify as a React Native super app with a custom design system. AI-powered spending categorization runs on-device via TensorFlow Lite for privacy. Biometric auth, end-to-end encryption, and real-time fraud detection make it enterprise-secure while feeling consumer-friendly.',
    keyFeatures: [
      'AI-powered spending categorization and budget insights',
      'Biometric authentication (Face ID + Fingerprint)',
      'Instant P2P transfers with QR code scanning',
      'Smart savings goals with automated round-ups',
      'Real-time push notifications for every transaction',
      'Dark mode with dynamic theming'
    ],
    designDirection: 'Dark, premium, and fluid. Inspired by luxury car dashboards — every number is crisp, every animation is purposeful. The gradient system uses deep navy-to-electric-blue to convey trust and innovation simultaneously.',
    outcome: '50,000+ downloads in the first 60 days. 4.8-star rating on both app stores. Average session duration of 4.2 minutes — 3x the industry average for banking apps.',
    fullStory: 'Vaultify started as a napkin sketch during a fintech hackathon. We took that raw energy and channeled it into a 6-month sprint, shipping an MVP in 3 months and iterating based on beta user feedback. The result is a product that users genuinely love using.',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f2?auto=format&fit=crop&q=80&w=2670',
    galleryImages: [
      'https://images.unsplash.com/photo-1616077168079-7e09a677fb2c?auto=format&fit=crop&q=80&w=2671',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2670',
      'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=2672',
      'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=2671'
    ],
    mobileMockups: [],
    desktopMockups: [],
    videoUrl: '',
    uiComponents: ['Bottom Tab Navigator', 'Spending Donut Chart', 'Transaction Feed Card', 'Biometric Auth Modal', 'QR Scanner Overlay', 'Budget Progress Ring'],
    systemDiagram: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'React Native app → Node.js API → MongoDB + Stripe + Firebase push notifications pipeline',
    testimonial: {
      quote: 'Our users say Vaultify is the first banking app that actually makes them want to check their finances. That\'s the highest compliment we could receive.',
      author: 'Arjun Mehta',
      role: 'CEO, Vaultify Inc.'
    },
    impact: '50K+ downloads in 60 days, 4.8★ App Store rating, $2.3M processed in first quarter.',
    relatedProjectIds: ['4'],
    url: 'https://vaultify.qoarc.com',
    metaTitle: 'Vaultify — AI-Powered Fintech App Case Study | QoArc',
    metaDescription: 'How QoArc designed and developed Vaultify, a next-gen mobile banking app with AI spending insights and biometric security for 50K+ users.',
    ogImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f2?auto=format&fit=crop&q=80&w=2670',
    isFeatured: true,
    isVisibleOnHome: true,
    status: 'published',
    order: 2
  },
  {
    id: '3',
    name: 'NeuralGrid — Smart City OS',
    client: 'EcoCity Solutions',
    slug: 'neuralgrid-smart-city',
    description: 'An AI-driven urban infrastructure operating system that optimizes energy distribution, traffic flow, and emergency response in real-time.',
    category: 'AI & IoT',
    industry: 'Smart Cities & Government',
    services: ['AI/ML Engineering', 'IoT Infrastructure', 'Dashboard Design', 'Data Pipeline Architecture'],
    timeline: '8 Months',
    year: '2023',
    techStack: ['Python', 'TensorFlow', 'React', 'D3.js', 'Apache Kafka', 'InfluxDB', 'Docker'],
    heroImage: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&q=80&w=2670',
    intro: 'Turning raw sensor data from 10,000+ IoT devices into actionable intelligence for city administrators.',
    duration: '8 Months',
    scope: 'Full AI pipeline: data ingestion from IoT sensors, ML model training, real-time dashboard, and alert system.',
    platform: 'Web Dashboard + IoT Edge Computing',
    deliverables: ['AI Prediction Engine', 'Real-Time Dashboard', 'IoT Gateway Software', 'API Documentation', 'Training Materials'],
    teamRole: 'AI Architecture & Frontend Lead',
    challenge: 'The city of Rajshahi was experiencing 30% energy wastage due to unoptimized power distribution. Traffic congestion added 45 minutes to average commutes. Emergency response times averaged 18 minutes — far above the safety threshold.',
    goal: 'Build an intelligent operating system that ingests data from thousands of IoT sensors deployed across the city and provides real-time optimization recommendations — reducing energy waste, traffic congestion, and emergency response times simultaneously.',
    solution: 'We built NeuralGrid — a graph neural network that models the entire city as an interconnected system. Energy nodes, traffic intersections, and emergency stations are all vertices in a dynamic graph. The AI predicts demand spikes 30 minutes ahead and automatically reroutes resources. A stunning D3.js dashboard gives administrators a god-view of the city.',
    keyFeatures: [
      'Graph Neural Network for city-wide optimization',
      'Real-time data ingestion from 10,000+ IoT sensors',
      'Predictive energy distribution (30-min lookahead)',
      'Automated traffic signal optimization',
      'Emergency response routing with ETA prediction',
      'Interactive 3D city visualization dashboard'
    ],
    designDirection: 'Command-center aesthetic. Deep blacks with neon data visualizations — think NASA mission control meets cyberpunk. Every data point glows, every chart animates, every alert demands attention. The UI makes administrators feel like they are piloting the city.',
    outcome: 'Energy wastage reduced from 30% to 11%. Average commute times dropped by 22 minutes. Emergency response times improved to under 9 minutes. The system now processes 2.4 million data points per hour.',
    fullStory: 'NeuralGrid began as a research collaboration between QoArc and EcoCity Solutions. We spent the first two months purely on data — understanding sensor schemas, cleaning noisy IoT feeds, and building the foundational data pipeline. The AI model went through 14 iterations before achieving production-grade accuracy. The result is a system that literally makes the city smarter every day.',
    imageUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&q=80&w=2670',
    galleryImages: [
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=2670',
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=2672',
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=2674',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=2670'
    ],
    mobileMockups: [],
    desktopMockups: [],
    videoUrl: '',
    uiComponents: ['3D City Map Renderer', 'Real-Time Sensor Grid', 'Energy Flow Sankey Chart', 'Alert Priority Queue', 'Predictive Timeline Graph', 'Heatmap Overlay Layer'],
    systemDiagram: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=2672',
    systemDiagramCaption: 'IoT sensors → Apache Kafka stream → TensorFlow inference engine → React dashboard with D3.js visualizations',
    testimonial: {
      quote: 'NeuralGrid transformed how we manage our city. We went from reactive firefighting to proactive optimization. The energy savings alone paid for the project in 4 months.',
      author: 'Eng. Kamal Hossain',
      role: 'Chief Smart City Officer, Rajshahi'
    },
    impact: '19% energy savings, 22-min commute reduction, 50% faster emergency response, 2.4M data points/hour.',
    relatedProjectIds: ['1'],
    url: 'https://neuralgrid.qoarc.com',
    metaTitle: 'NeuralGrid — AI-Powered Smart City OS Case Study | QoArc',
    metaDescription: 'How QoArc engineered NeuralGrid, an AI operating system for smart cities that reduced energy waste by 19% and cut emergency response times in half.',
    ogImage: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&q=80&w=2670',
    isFeatured: true,
    isVisibleOnHome: true,
    status: 'published',
    order: 3
  },
  {
    id: '4',
    name: 'Lumière — Luxury Brand System',
    client: 'Maison Lumière Paris',
    slug: 'lumiere-brand-identity',
    description: 'A complete brand identity overhaul for a Parisian luxury fashion house — from logo redesign to a full digital design system.',
    category: 'Branding',
    industry: 'Fashion & Luxury',
    services: ['Brand Strategy', 'Visual Identity Design', 'Typography', 'Brand Guidelines', 'Packaging Design'],
    timeline: '3 Months',
    year: '2024',
    techStack: ['Figma', 'Adobe Illustrator', 'After Effects', 'Blender', 'Webflow'],
    heroImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=2670',
    intro: 'Reimagining a 40-year-old fashion brand for the digital-first generation without sacrificing its heritage.',
    duration: '3 Months',
    scope: 'Complete brand overhaul: logo, typography, color system, packaging, digital templates, and brand guidelines document.',
    platform: 'Cross-Platform (Print + Digital)',
    deliverables: ['Logo System (28 variants)', 'Brand Guidelines (120 pages)', 'Typography Suite', 'Color System', 'Packaging Templates', 'Social Media Kit', 'Email Templates'],
    teamRole: 'Creative Director & Brand Strategist',
    challenge: 'Maison Lumière had a 40-year heritage but their visual identity was stuck in the 1990s. Their logo didn\'t scale for digital, their color palette felt dated, and their packaging looked indistinguishable from fast-fashion competitors. They were losing market share to younger, digitally-native luxury brands.',
    goal: 'Create a modern brand identity that honors the house\'s Parisian heritage while feeling fresh, digital-native, and unmistakably premium. The new system must work flawlessly from a 16px favicon to a 20-foot billboard.',
    solution: 'We developed a modular brand system anchored by a reimagined wordmark that uses custom-drawn letterforms inspired by Art Deco geometry. The color palette shifts from their old burgundy-gold to a sophisticated charcoal-champagne-ivory trio. Every element scales perfectly from social thumbnails to storefront signage thanks to a responsive grid system.',
    keyFeatures: [
      'Custom-drawn wordmark with 28 responsive variants',
      'Modular logo system (icon, wordmark, lockup, monogram)',
      'Responsive typography scale with 3 custom weights',
      'Charcoal-Champagne-Ivory color architecture',
      'Sustainable packaging system with embossed details',
      '120-page brand guidelines with usage rules'
    ],
    designDirection: 'Quiet luxury. No gradients, no noise — just impeccable spacing, restrained color, and typography that whispers confidence. The brand system channels Dieter Rams\' "less but better" philosophy through a Parisian lens.',
    outcome: 'Brand recognition scores increased by 47% in target demographics (25-40). Instagram engagement rose by 280% after the rebrand. The packaging redesign reduced material costs by 15% while elevating perceived value. Vogue Paris featured the rebrand as "Identity of the Year."',
    fullStory: 'This project was a masterclass in restraint. The client initially wanted a radical departure, but our research showed that their heritage was an asset, not a liability. We spent the first month purely on strategy — understanding what to keep, what to evolve, and what to discard. The final identity feels both timeless and contemporary.',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=2670',
    galleryImages: [
      'https://images.unsplash.com/photo-1493655161922-ef98929de9d8?auto=format&fit=crop&q=80&w=2670',
      'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?auto=format&fit=crop&q=80&w=2669',
      'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=2715',
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&q=80&w=2632'
    ],
    mobileMockups: [],
    desktopMockups: [],
    videoUrl: '',
    uiComponents: ['Logo Variant Grid', 'Color Swatch Palette', 'Typography Specimen Sheet', 'Packaging Mockup Viewer', 'Before/After Slider', 'Brand Guidelines PDF Viewer'],
    systemDiagram: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=2715',
    systemDiagramCaption: 'Brand system architecture: Core Identity → Digital Extensions → Print Applications → Social Templates',
    testimonial: {
      quote: 'QoArc understood something most agencies missed — our brand needed evolution, not revolution. The result is an identity that feels like it has always existed, yet is unmistakably modern.',
      author: 'Élise Moreau',
      role: 'Creative Director, Maison Lumière'
    },
    impact: '47% increase in brand recognition, 280% Instagram engagement boost, featured in Vogue Paris.',
    relatedProjectIds: ['2'],
    url: 'https://lumiere.qoarc.com',
    metaTitle: 'Lumière — Luxury Brand Identity Case Study | QoArc',
    metaDescription: 'How QoArc reimagined a 40-year-old Parisian fashion house for the digital age with a modular brand system that increased recognition by 47%.',
    ogImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false,
    isVisibleOnHome: true,
    status: 'published',
    order: 4
  },
  {
    id: '5',
    name: 'MediSync — Healthcare SaaS',
    client: 'MediSync Health Technologies',
    slug: 'medisync-healthcare-saas',
    description: 'A cloud-based electronic health record (EHR) platform that connects clinics, pharmacies, and patients in a unified ecosystem.',
    category: 'Web',
    industry: 'Healthcare & SaaS',
    services: ['SaaS Product Design', 'Full-Stack Development', 'HIPAA Compliance', 'API Development'],
    timeline: '10 Months',
    year: '2023',
    techStack: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'Redis', 'AWS', 'Docker'],
    heroImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=2670',
    intro: 'Building the connective tissue for modern healthcare — a platform where every stakeholder speaks the same digital language.',
    duration: '10 Months',
    scope: 'Full SaaS product: multi-tenant architecture, patient portal, clinic dashboard, pharmacy integration, and mobile-responsive PWA.',
    platform: 'Web (SaaS) + PWA',
    deliverables: ['Multi-Tenant SaaS Platform', 'Patient Portal', 'Clinic Dashboard', 'Pharmacy Integration API', 'Mobile PWA', 'HIPAA Compliance Documentation'],
    teamRole: 'Technical Architect & Product Lead',
    challenge: 'Healthcare in South Asia operates in silos. Clinics use paper records, pharmacies have no visibility into prescriptions, and patients carry their medical history in plastic bags. This fragmentation leads to medication errors, duplicate tests, and delayed diagnoses that cost lives.',
    goal: 'Build a unified healthcare platform that digitizes patient records, enables real-time prescription sharing between clinics and pharmacies, gives patients ownership of their data, and does all of this while remaining HIPAA-compliant and affordable for small clinics.',
    solution: 'MediSync is a multi-tenant SaaS platform built on Next.js with a PostgreSQL backbone. Each clinic gets an isolated tenant with customizable workflows. The pharmacy integration API enables real-time prescription verification. Patients access a Progressive Web App that works offline — critical for areas with unreliable internet. Role-based access control and AES-256 encryption ensure compliance.',
    keyFeatures: [
      'Multi-tenant architecture with isolated data per clinic',
      'Real-time prescription sharing with pharmacy network',
      'Offline-capable Progressive Web App for patients',
      'HIPAA-compliant with AES-256 encryption',
      'Customizable clinical workflows per specialty',
      'Automated appointment scheduling with SMS reminders',
      'Analytics dashboard with patient outcome tracking'
    ],
    designDirection: 'Clinical precision meets human warmth. Clean white spaces with subtle green accents evoke sterile trust without feeling cold. The typography prioritizes readability — doctors scan hundreds of records daily, so every pixel serves a functional purpose.',
    outcome: '127 clinics onboarded in the first quarter. Patient record retrieval time dropped from 12 minutes (paper) to 3 seconds. Medication errors reduced by 34%. The platform now manages 45,000+ active patient records across 3 cities.',
    fullStory: 'MediSync was born out of frustration. Our co-founder watched a family member receive the wrong medication because a pharmacist couldn\'t read a doctor\'s handwriting. We spent 10 months building a system that ensures this never happens again. The technical challenges were immense — multi-tenancy, HIPAA compliance, offline-first PWA — but the human impact makes every line of code worth it.',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=2670',
    galleryImages: [
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=2670',
      'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&q=80&w=2564',
      'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&q=80&w=2631',
      'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?auto=format&fit=crop&q=80&w=2672'
    ],
    mobileMockups: [],
    desktopMockups: [],
    videoUrl: '',
    uiComponents: ['Patient Record Accordion', 'Prescription Builder Form', 'Pharmacy Verification Badge', 'Appointment Calendar Widget', 'Clinical Workflow Stepper', 'Offline Sync Indicator'],
    systemDiagram: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'Multi-tenant SaaS: Next.js → Prisma ORM → PostgreSQL (per-tenant) with Redis cache and AWS deployment',
    testimonial: {
      quote: 'MediSync eliminated the chaos in our clinic. We went from losing patient files to having instant access to complete medical histories. It\'s genuinely saving lives.',
      author: 'Dr. Anwar Hussain',
      role: 'Chief Medical Officer, Dhaka Central Clinic'
    },
    impact: '127 clinics onboarded, 45K+ patient records, 34% reduction in medication errors, 3-second record retrieval.',
    relatedProjectIds: ['1', '3'],
    url: 'https://medisync.qoarc.com',
    metaTitle: 'MediSync — Healthcare SaaS Platform Case Study | QoArc',
    metaDescription: 'How QoArc built MediSync, a HIPAA-compliant healthcare SaaS that connects clinics, pharmacies, and patients — serving 45,000+ records across 127 clinics.',
    ogImage: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false,
    isVisibleOnHome: true,
    status: 'published',
    order: 5
  },
  {
    id: '6',
    name: 'Orbis — E-Commerce Engine',
    client: 'Orbis Retail Group',
    slug: 'orbis-ecommerce',
    description: 'A headless e-commerce platform with AI product recommendations, multi-currency checkout, and an admin inventory system.',
    category: 'Web',
    industry: 'E-Commerce & Retail',
    services: ['Headless Commerce', 'Full-Stack Development', 'Payment Integration', 'UX Design'],
    timeline: '5 Months',
    year: '2024',
    techStack: ['Next.js', 'Shopify Storefront API', 'Stripe', 'Algolia', 'Sanity CMS', 'Vercel'],
    heroImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=2670',
    intro: 'A blazing-fast headless commerce experience that converts browsers into buyers.',
    duration: '5 Months',
    scope: 'Headless storefront, checkout flow, inventory CMS, analytics dashboard.',
    platform: 'Web (Headless)',
    deliverables: ['Headless Storefront', 'Checkout System', 'Inventory CMS', 'Analytics Portal'],
    teamRole: 'Commerce Architecture Lead',
    challenge: 'Orbis was stuck on a monolithic Magento instance that took 6 seconds to load product pages. Cart abandonment sat at 74%.',
    goal: 'Build a sub-second headless storefront that integrates with their existing Shopify backend while adding AI-powered product discovery.',
    solution: 'We decoupled the frontend using Next.js with ISR, connected Shopify via the Storefront API, and layered Algolia for instant search. Stripe handles multi-currency checkout with 3D Secure.',
    keyFeatures: ['AI product recommendations via Algolia', 'Sub-200ms page loads with ISR', 'Multi-currency Stripe checkout', 'Real-time inventory sync', 'Wishlist & cart persistence', 'Admin inventory dashboard'],
    designDirection: 'Editorial luxury. Large product photography, minimal UI chrome, and typography-driven layouts inspired by high-fashion lookbooks.',
    outcome: 'Page load dropped from 6s to 0.8s. Cart abandonment reduced to 31%. Revenue increased by 128% in the first quarter post-launch.',
    fullStory: 'Orbis needed speed above all else. We rebuilt their entire storefront in 5 months, proving that headless commerce is not just a buzzword — it is a revenue multiplier.',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=2670',
    galleryImages: ['https://images.unsplash.com/photo-1472851294608-062f824d29cc?auto=format&fit=crop&q=80&w=2670', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=2670'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Product Card Grid', 'Infinite Scroll Loader', 'Quick-View Modal', 'Cart Drawer Sidebar', 'Filter Accordion', 'Size Selector Chips'],
    systemDiagram: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=2426',
    systemDiagramCaption: 'Next.js (Vercel) → Shopify Storefront API → Algolia Search → Stripe Checkout → Sanity CMS',
    testimonial: { quote: 'Our revenue doubled. QoArc turned our slow storefront into a conversion machine.', author: 'Sarah Chen', role: 'VP Digital, Orbis Retail' },
    impact: '128% revenue increase, 0.8s load time, cart abandonment down to 31%.',
    relatedProjectIds: ['2'], url: 'https://orbis.qoarc.com',
    metaTitle: 'Orbis — Headless E-Commerce Case Study | QoArc',
    metaDescription: 'How QoArc built a headless e-commerce platform that cut load times by 87% and doubled revenue for Orbis Retail.',
    ogImage: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false, isVisibleOnHome: true, status: 'published', order: 6
  },
  {
    id: '7',
    name: 'PulseTrack — Fitness Companion',
    client: 'PulseTrack Health',
    slug: 'pulsetrack-fitness-app',
    description: 'A wearable-connected fitness app with real-time heart rate monitoring, AI workout plans, and social challenges.',
    category: 'App',
    industry: 'Health & Fitness',
    services: ['Mobile App Development', 'Wearable Integration', 'UI/UX Design', 'Backend API'],
    timeline: '7 Months',
    year: '2023',
    techStack: ['Flutter', 'Dart', 'Firebase', 'HealthKit', 'Google Fit API', 'Node.js'],
    heroImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&q=80&w=2670',
    intro: 'Making fitness data beautiful, actionable, and social.',
    duration: '7 Months',
    scope: 'Cross-platform app with wearable SDK integrations and social features.',
    platform: 'iOS & Android (Flutter)',
    deliverables: ['Cross-Platform App', 'Wearable SDK', 'Social Features', 'Admin Dashboard'],
    teamRole: 'Product & Engineering Lead',
    challenge: 'Existing fitness apps felt clinical and isolating. Users dropped off after 2 weeks because there was no social accountability or personalization.',
    goal: 'Build a fitness companion that feels like a game — with social challenges, AI-personalized workouts, and beautiful data visualizations.',
    solution: 'PulseTrack uses Flutter for a single codebase across iOS/Android. HealthKit and Google Fit provide real-time biometrics. An AI engine adapts workout difficulty based on recovery metrics. Social challenges with leaderboards drive retention.',
    keyFeatures: ['Real-time heart rate zones', 'AI-adaptive workout plans', 'Social challenges & leaderboards', 'Wearable device sync', 'Sleep quality tracking', 'Animated progress rings'],
    designDirection: 'Energetic gradients with a dark base. Every stat glows. Every achievement pops. The UI should make users feel like athletes reviewing performance data.',
    outcome: '200K downloads in 6 months. Day-30 retention at 41% vs industry average of 12%. Featured in App Store "Apps We Love."',
    fullStory: 'PulseTrack was built with a "fitness for everyone" philosophy. We tested with 500 beta users ranging from couch potatoes to marathon runners.',
    imageUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&q=80&w=2670',
    galleryImages: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80&w=2670', 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=2670'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Heart Rate Zone Ring', 'Workout Timer Dial', 'Activity Feed Card', 'Challenge Leaderboard', 'Progress Calendar Heatmap', 'Recovery Score Gauge'],
    systemDiagram: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'Flutter app → HealthKit/Google Fit SDK → Firebase Firestore → Node.js AI engine → Push notifications',
    testimonial: { quote: 'PulseTrack made me actually enjoy working out. The social challenges keep me accountable.', author: 'Jake Morrison', role: 'Beta User & Marathon Runner' },
    impact: '200K downloads, 41% D30 retention, App Store featured.',
    relatedProjectIds: ['2'], url: 'https://pulsetrack.qoarc.com',
    metaTitle: 'PulseTrack — AI Fitness App Case Study | QoArc',
    metaDescription: 'How QoArc built PulseTrack, a wearable-connected fitness app with 200K downloads and 3x industry retention rates.',
    ogImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false, isVisibleOnHome: true, status: 'published', order: 7
  },
  {
    id: '8',
    name: 'AgroVision — Precision Agriculture',
    client: 'AgroVision Technologies',
    slug: 'agrovision-precision-ag',
    description: 'A drone-powered crop monitoring system with satellite imagery analysis and yield prediction for large-scale farms.',
    category: 'AI & IoT',
    industry: 'Agriculture & AgriTech',
    services: ['AI/ML Development', 'Satellite Image Processing', 'IoT Dashboard', 'Mobile App'],
    timeline: '9 Months',
    year: '2023',
    techStack: ['Python', 'PyTorch', 'Google Earth Engine', 'React', 'Node.js', 'MQTT', 'PostgreSQL'],
    heroImage: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&q=80&w=2670',
    intro: 'Bringing satellite-grade intelligence to every farmer\'s fingertips.',
    duration: '9 Months',
    scope: 'End-to-end precision agriculture platform with drone integration, ML models, and farmer-facing dashboard.',
    platform: 'Web + Mobile (PWA)',
    deliverables: ['Crop Health ML Model', 'Satellite Imagery Pipeline', 'Farmer Dashboard', 'Drone Integration SDK', 'Mobile PWA'],
    teamRole: 'AI & Product Engineering Lead',
    challenge: 'Farmers in developing regions lose 20-40% of crops annually due to late detection of diseases, pests, and water stress. Traditional scouting covers only 5% of farmland.',
    goal: 'Build an affordable AI platform that uses satellite and drone imagery to detect crop anomalies weeks before they become visible to the naked eye.',
    solution: 'AgroVision processes multispectral satellite imagery through a PyTorch-based CNN that classifies crop health into 7 categories. Drone flyovers provide cm-resolution data for targeted intervention. A simple PWA delivers alerts and recommendations in local languages.',
    keyFeatures: ['Multispectral crop health classification', 'Drone flight path optimization', 'Yield prediction with 89% accuracy', 'Weather-integrated irrigation scheduler', 'Offline-capable PWA for rural areas', 'Multilingual voice alerts'],
    designDirection: 'Earthy and functional. Greens, browns, and warm yellows dominate. The UI prioritizes large touch targets and simple language — many users interact with gloves or in bright sunlight.',
    outcome: 'Deployed across 12,000 hectares. Crop loss reduced by 27%. Early disease detection rate improved from 15% to 78%. ROI for farmers: 340% in the first season.',
    fullStory: 'AgroVision started as a university research project that we commercialized. The hardest challenge was not the AI — it was making the interface usable for farmers who had never used a smartphone app.',
    imageUrl: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&q=80&w=2670',
    galleryImages: ['https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&q=80&w=2670', 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&q=80&w=2670'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Satellite Map Overlay', 'NDVI Heatmap Layer', 'Crop Health Score Badge', 'Drone Path Planner', 'Weather Forecast Strip', 'Yield Prediction Chart'],
    systemDiagram: 'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'Google Earth Engine → PyTorch inference → MQTT broker → React dashboard + PWA with offline sync',
    testimonial: { quote: 'I saved my entire rice harvest this season because AgroVision detected blight 3 weeks early. This technology is a gift.', author: 'Farmer Abdul Karim', role: 'Rice Farmer, Rangpur' },
    impact: '12,000 hectares, 27% crop loss reduction, 78% early detection rate.',
    relatedProjectIds: ['3'], url: 'https://agrovision.qoarc.com',
    metaTitle: 'AgroVision — AI Precision Agriculture Case Study | QoArc',
    metaDescription: 'How QoArc built AgroVision, a drone-powered crop monitoring system that reduced crop loss by 27% across 12,000 hectares.',
    ogImage: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&q=80&w=2670',
    isFeatured: true, isVisibleOnHome: true, status: 'published', order: 8
  },
  {
    id: '9',
    name: 'Noctis — Dark Design System',
    client: 'Noctis Digital Agency',
    slug: 'noctis-design-system',
    description: 'A comprehensive dark-mode-first design system with 120+ components, accessibility-first tokens, and Figma-to-code pipeline.',
    category: 'Branding',
    industry: 'Design & Technology',
    services: ['Design Systems', 'Component Library', 'Figma Plugin Development', 'Documentation'],
    timeline: '4 Months',
    year: '2024',
    techStack: ['Figma', 'Storybook', 'React', 'Styled Components', 'Chromatic', 'MDX'],
    heroImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2670',
    intro: 'A design system so robust that designers and developers speak the same language.',
    duration: '4 Months',
    scope: 'Complete design system: Figma library, React component library, Storybook documentation, and CI/CD pipeline.',
    platform: 'Cross-Platform (Design + Code)',
    deliverables: ['Figma Component Library', 'React Component Package', 'Storybook Documentation', 'Figma Plugin', 'Migration Guide'],
    teamRole: 'Design System Architect',
    challenge: 'Noctis had 6 products with 6 different design languages. Every new feature required custom components, creating a maintenance nightmare.',
    goal: 'Create a unified dark-mode-first design system that serves all 6 products with consistent, accessible, and performant components.',
    solution: 'We built Noctis DS with design tokens at its core — every color, spacing, and typography value is a token that syncs between Figma and code. 120+ components cover 95% of UI needs. A custom Figma plugin auto-generates React code from designs.',
    keyFeatures: ['120+ production-ready components', 'Design tokens with Figma sync', 'WCAG 2.1 AA compliance', 'Auto-generated React code from Figma', 'Dark/light mode with one toggle', 'Storybook with interactive docs'],
    designDirection: 'Systematic elegance. Every component follows a strict 4px grid. Dark mode is the primary theme, with a carefully calibrated contrast ratio system.',
    outcome: 'Design-to-development handoff time reduced by 70%. Component reuse rate across products: 89%. Bug reports related to UI inconsistency dropped to near zero.',
    fullStory: 'Building a design system is like writing a dictionary — it requires discipline, consistency, and the humility to know you cannot predict every use case.',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2670',
    galleryImages: ['https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&q=80&w=2670', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=2672'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Token Inspector Panel', 'Component Variant Picker', 'A11y Contrast Checker', 'Code Preview Block', 'Theme Toggle Switch', 'Grid Overlay Tool'],
    systemDiagram: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'Figma Plugin → Design Tokens JSON → Style Dictionary → React Components → Storybook → Chromatic CI',
    testimonial: { quote: 'Noctis DS cut our design-to-dev time by 70%. It is the single best investment we have made.', author: 'Maya Patel', role: 'Head of Design, Noctis Digital' },
    impact: '70% faster handoff, 89% component reuse, near-zero UI inconsistency bugs.',
    relatedProjectIds: ['4'], url: 'https://noctis.qoarc.com',
    metaTitle: 'Noctis — Dark Design System Case Study | QoArc',
    metaDescription: 'How QoArc architected Noctis DS, a 120+ component design system that reduced design-to-dev handoff by 70%.',
    ogImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false, isVisibleOnHome: true, status: 'published', order: 9
  },
  {
    id: '10',
    name: 'Zenith — EdTech Platform',
    client: 'Zenith Learning',
    slug: 'zenith-edtech',
    description: 'An adaptive learning platform with AI-powered course recommendations, live classrooms, and gamified progress tracking.',
    category: 'Web',
    industry: 'Education & EdTech',
    services: ['Full-Stack Development', 'AI Integration', 'Video Streaming', 'Gamification Design'],
    timeline: '8 Months',
    year: '2024',
    techStack: ['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL', 'WebRTC', 'OpenAI API', 'AWS'],
    heroImage: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=2674',
    intro: 'Making education adaptive, engaging, and accessible to every learner.',
    duration: '8 Months',
    scope: 'Full LMS: course builder, live video, AI tutor, gamification engine, analytics.',
    platform: 'Web (SaaS) + Mobile PWA',
    deliverables: ['Adaptive LMS Platform', 'Live Classroom System', 'AI Tutor Chatbot', 'Gamification Engine', 'Instructor Dashboard'],
    teamRole: 'Technical Architect & AI Lead',
    challenge: 'Traditional LMS platforms treat every student the same. Completion rates hover around 8% because content is linear, static, and disengaging.',
    goal: 'Build an adaptive platform where the AI understands each student\'s learning pace, style, and gaps — then dynamically adjusts content difficulty and sequence.',
    solution: 'Zenith uses OpenAI to analyze student interaction patterns and dynamically reorder course content. WebRTC powers live classrooms with real-time whiteboarding. A gamification engine with XP, badges, and streaks drives daily engagement.',
    keyFeatures: ['AI-adaptive course sequencing', 'Live classroom with whiteboard', 'XP & badge gamification system', 'AI tutor chatbot for Q&A', 'Progress analytics for instructors', 'Offline content access via PWA'],
    designDirection: 'Playful yet professional. Soft gradients, rounded elements, and micro-celebrations for achievements. The UI makes learning feel like a game without being childish.',
    outcome: 'Course completion rates jumped from 8% to 47%. Daily active users grew 5x in 3 months. Instructor onboarding time reduced to under 30 minutes.',
    fullStory: 'Zenith is proof that education does not have to be boring. Every feature was designed with one question: "Does this make the student want to come back tomorrow?"',
    imageUrl: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=2674',
    galleryImages: ['https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=2671', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=2632'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Lesson Player with Chapters', 'XP Progress Bar', 'Badge Achievement Modal', 'Live Whiteboard Canvas', 'AI Chat Interface', 'Course Roadmap Timeline'],
    systemDiagram: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=2671',
    systemDiagramCaption: 'Next.js → OpenAI API (adaptive engine) → WebRTC (live rooms) → PostgreSQL → AWS S3 (video CDN)',
    testimonial: { quote: 'Zenith tripled our student engagement. The AI tutor is like having a personal mentor for every student.', author: 'Prof. Nadia Ahmed', role: 'Founder, Zenith Learning' },
    impact: '47% course completion (vs 8% baseline), 5x DAU growth, 30-min instructor onboarding.',
    relatedProjectIds: ['5'], url: 'https://zenith.qoarc.com',
    metaTitle: 'Zenith — AI EdTech Platform Case Study | QoArc',
    metaDescription: 'How QoArc built Zenith, an adaptive learning platform that increased course completion rates from 8% to 47%.',
    ogImage: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=2674',
    isFeatured: true, isVisibleOnHome: true, status: 'published', order: 10
  },
  {
    id: '11',
    name: 'FleetPulse — Logistics OS',
    client: 'TransLogix Corp.',
    slug: 'fleetpulse-logistics',
    description: 'A real-time fleet management system with route optimization, driver analytics, and predictive maintenance alerts.',
    category: 'App',
    industry: 'Logistics & Transportation',
    services: ['Mobile App Development', 'Backend Engineering', 'IoT Integration', 'Maps & Routing'],
    timeline: '6 Months',
    year: '2024',
    techStack: ['React Native', 'Go', 'PostgreSQL', 'Google Maps API', 'MQTT', 'Grafana'],
    heroImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=2670',
    intro: 'Putting fleet managers in the driver\'s seat with real-time visibility across every vehicle.',
    duration: '6 Months',
    scope: 'Driver app, manager dashboard, IoT OBD integration, route optimization engine.',
    platform: 'iOS & Android + Web Dashboard',
    deliverables: ['Driver Mobile App', 'Manager Dashboard', 'OBD IoT Integration', 'Route Optimizer', 'Reporting Suite'],
    teamRole: 'Full-Stack & IoT Lead',
    challenge: 'TransLogix managed 800+ vehicles with spreadsheets and phone calls. Fuel costs were 23% above industry average. Delivery ETAs were unreliable.',
    goal: 'Build a real-time fleet OS that optimizes routes, monitors driver behavior, predicts vehicle maintenance needs, and provides accurate delivery ETAs.',
    solution: 'FleetPulse connects to OBD-II sensors in every vehicle via MQTT, streaming telemetry to a Go backend. A route optimization engine using Google Maps reduces fuel consumption. A React Native driver app provides turn-by-turn navigation and delivery confirmations.',
    keyFeatures: ['Real-time GPS fleet tracking', 'AI route optimization', 'OBD-II telemetry ingestion', 'Driver behavior scoring', 'Predictive maintenance alerts', 'Customer delivery notifications'],
    designDirection: 'Utilitarian precision. Clean data tables, real-time maps, and status indicators. The manager dashboard feels like an air traffic control system.',
    outcome: 'Fuel costs reduced by 19%. On-time deliveries improved from 71% to 94%. Vehicle downtime decreased by 35% through predictive maintenance.',
    fullStory: 'FleetPulse proved that even the most traditional industries can be transformed with the right technology. The hardest part was convincing 800 drivers to adopt the new app.',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=2670',
    galleryImages: ['https://images.unsplash.com/photo-1494412574643-ff11b0a5eb19?auto=format&fit=crop&q=80&w=2670', 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&q=80&w=2670'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Live Map with Vehicle Pins', 'Route Comparison Panel', 'Driver Score Radar Chart', 'Maintenance Alert Banner', 'Delivery Timeline Strip', 'Fuel Efficiency Gauge'],
    systemDiagram: 'https://images.unsplash.com/photo-1494412574643-ff11b0a5eb19?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'OBD-II sensors → MQTT broker → Go backend → PostgreSQL → React Native app + Grafana dashboards',
    testimonial: { quote: 'FleetPulse saved us $1.2M in fuel costs in the first year. The ROI was immediate.', author: 'Razib Ahmed', role: 'COO, TransLogix Corp.' },
    impact: '19% fuel savings, 94% on-time delivery, 35% less vehicle downtime.',
    relatedProjectIds: ['3'], url: 'https://fleetpulse.qoarc.com',
    metaTitle: 'FleetPulse — Logistics OS Case Study | QoArc',
    metaDescription: 'How QoArc built FleetPulse, a real-time fleet management system that cut fuel costs by 19% for 800+ vehicles.',
    ogImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false, isVisibleOnHome: true, status: 'published', order: 11
  },
  {
    id: '12',
    name: 'Sentient — AI Customer Support',
    client: 'Sentient AI Labs',
    slug: 'sentient-ai-support',
    description: 'An AI-first customer support platform with natural language understanding, ticket routing, and human escalation workflows.',
    category: 'AI & IoT',
    industry: 'SaaS & Enterprise',
    services: ['AI/ML Development', 'NLP Engineering', 'Full-Stack Development', 'API Design'],
    timeline: '5 Months',
    year: '2024',
    techStack: ['Python', 'LangChain', 'OpenAI GPT-4', 'FastAPI', 'React', 'Redis', 'PostgreSQL'],
    heroImage: 'https://images.unsplash.com/photo-1531746790095-e5e3c0024f3e?auto=format&fit=crop&q=80&w=2670',
    intro: 'Support that understands before you finish typing.',
    duration: '5 Months',
    scope: 'AI chatbot, ticket management system, knowledge base builder, analytics dashboard.',
    platform: 'Web (SaaS) + Embedded Widget',
    deliverables: ['AI Chatbot Engine', 'Ticket Management System', 'Knowledge Base Builder', 'Embeddable Widget', 'Analytics Dashboard'],
    teamRole: 'AI Architecture Lead',
    challenge: 'Enterprise support teams handle 10,000+ tickets monthly. 60% are repetitive questions that could be automated. Average response time: 4 hours.',
    goal: 'Build an AI system that resolves 70%+ of support queries automatically while seamlessly escalating complex issues to human agents with full context.',
    solution: 'Sentient uses LangChain with GPT-4 to understand customer intent, search a RAG-powered knowledge base, and generate accurate responses. When confidence is low, it routes to humans with a pre-written draft response and context summary.',
    keyFeatures: ['RAG-powered knowledge base', 'Intent classification with 94% accuracy', 'Auto-draft responses for agents', 'Sentiment analysis and escalation', 'Multilingual support (12 languages)', 'Embeddable one-line widget'],
    designDirection: 'Clean, trustworthy, and invisible. The chatbot should feel like talking to a knowledgeable human, not a robot. Minimal branding, maximum helpfulness.',
    outcome: 'Automated resolution rate: 73%. Average response time dropped from 4 hours to 8 seconds. Customer satisfaction (CSAT) improved by 34%.',
    fullStory: 'Sentient proves that AI does not replace human support — it amplifies it. Agents now focus on complex, high-value conversations while the AI handles the rest.',
    imageUrl: 'https://images.unsplash.com/photo-1531746790095-e5e3c0024f3e?auto=format&fit=crop&q=80&w=2670',
    galleryImages: ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=2670', 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=2670'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Chat Bubble Stream', 'Confidence Score Indicator', 'Knowledge Base Card', 'Agent Handoff Modal', 'Sentiment Emotion Chip', 'Ticket Priority Queue'],
    systemDiagram: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'Customer widget → FastAPI → LangChain + GPT-4 → RAG Knowledge Base → Redis queue → Human agent dashboard',
    testimonial: { quote: 'Sentient handles 73% of our tickets automatically. Our support team now focuses on what matters.', author: 'Lisa Wong', role: 'VP Support, Sentient AI Labs' },
    impact: '73% automated resolution, 8-second response time, 34% CSAT improvement.',
    relatedProjectIds: ['3', '5'], url: 'https://sentient.qoarc.com',
    metaTitle: 'Sentient — AI Customer Support Case Study | QoArc',
    metaDescription: 'How QoArc built Sentient, an AI support platform that resolves 73% of tickets automatically with 8-second response times.',
    ogImage: 'https://images.unsplash.com/photo-1531746790095-e5e3c0024f3e?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false, isVisibleOnHome: true, status: 'published', order: 12
  },
  {
    id: '13',
    name: 'Aether — SaaS Dashboard Kit',
    client: 'Aether Technologies',
    slug: 'aether-dashboard-kit',
    description: 'A white-label SaaS analytics dashboard with real-time charts, multi-tenant architecture, and embeddable report widgets.',
    category: 'Web',
    industry: 'SaaS & Analytics',
    services: ['Dashboard Design', 'Full-Stack Development', 'Data Visualization', 'White-Label Architecture'],
    timeline: '4 Months',
    year: '2024',
    techStack: ['Next.js', 'Recharts', 'D3.js', 'PostgreSQL', 'Prisma', 'Tailwind CSS'],
    heroImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2670',
    intro: 'Analytics so beautiful, clients will think you built it custom.',
    duration: '4 Months',
    scope: 'White-label dashboard framework, chart library, tenant management, embed SDK.',
    platform: 'Web (White-Label SaaS)',
    deliverables: ['Dashboard Framework', 'Chart Component Library', 'Tenant Manager', 'Embed SDK', 'Theme Engine'],
    teamRole: 'Frontend Architecture Lead',
    challenge: 'SaaS companies spend 3-6 months building analytics dashboards from scratch. Most look mediocre because teams prioritize data over design.',
    goal: 'Create a drop-in dashboard kit that any SaaS can white-label in days, with production-grade charts, real-time data, and customizable themes.',
    solution: 'Aether is a Next.js-based dashboard framework with Recharts and D3.js under the hood. A theme engine allows complete visual customization via CSS variables. Multi-tenant isolation ensures data security across clients.',
    keyFeatures: ['30+ chart types with animations', 'White-label theme engine', 'Multi-tenant data isolation', 'Embeddable report widgets', 'Export to PDF/CSV/PNG', 'Real-time WebSocket data'],
    designDirection: 'Data-forward minimalism. Charts are the heroes. The surrounding UI is invisible. Carefully tuned colors ensure data readability across all chart types.',
    outcome: '18 SaaS companies adopted Aether in the first quarter. Average integration time: 3 days. Customer-reported development time savings: 4 months.',
    fullStory: 'Aether was born from our own frustration building dashboards for clients. We extracted the best patterns from 20+ projects into a reusable framework.',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2670',
    galleryImages: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=2426', 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&q=80&w=2676'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Area Chart with Gradient', 'KPI Stat Card', 'Data Table with Sort', 'Date Range Picker', 'Theme Palette Editor', 'Export Options Dropdown'],
    systemDiagram: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=2426',
    systemDiagramCaption: 'Next.js framework → Recharts/D3.js → WebSocket server → PostgreSQL → Theme Engine (CSS vars)',
    testimonial: { quote: 'We integrated Aether in 2 days. Our clients think we built the analytics from scratch.', author: 'Tom Bradley', role: 'CTO, Aether Technologies' },
    impact: '18 SaaS adopters, 3-day integration, 4-month dev time savings per client.',
    relatedProjectIds: ['6', '10'], url: 'https://aether.qoarc.com',
    metaTitle: 'Aether — White-Label SaaS Dashboard Case Study | QoArc',
    metaDescription: 'How QoArc built Aether, a white-label analytics dashboard adopted by 18 SaaS companies with 3-day integration times.',
    ogImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false, isVisibleOnHome: true, status: 'published', order: 13
  },
  {
    id: '14',
    name: 'Kinetic — Motion Branding',
    client: 'Kinetic Sports Media',
    slug: 'kinetic-motion-branding',
    description: 'A kinetic brand identity for a sports media company — combining motion graphics, 3D assets, and broadcast-ready design templates.',
    category: 'Branding',
    industry: 'Sports & Media',
    services: ['Brand Identity', 'Motion Graphics', '3D Asset Creation', 'Broadcast Design'],
    timeline: '3 Months',
    year: '2024',
    techStack: ['After Effects', 'Cinema 4D', 'Figma', 'Lottie', 'Adobe Premiere'],
    heroImage: 'https://images.unsplash.com/photo-1461896836934-bd45ba22fc82?auto=format&fit=crop&q=80&w=2670',
    intro: 'A brand that moves as fast as the sports it covers.',
    duration: '3 Months',
    scope: 'Full brand identity with motion-first approach: logo animations, broadcast templates, social kits, 3D assets.',
    platform: 'Broadcast + Digital + Social',
    deliverables: ['Animated Logo (12 variants)', 'Broadcast Lower Thirds', '3D Stadium Assets', 'Social Template Kit', 'Motion Guidelines'],
    teamRole: 'Creative Director & Motion Lead',
    challenge: 'Kinetic\'s brand was static in a world where sports content is consumed in 15-second TikToks and fast-paced broadcasts. Their competitors had dynamic, animated identities that made Kinetic look outdated.',
    goal: 'Create a brand identity where motion is not an afterthought but the core — every asset designed to move, every element built for broadcast speed.',
    solution: 'We designed a geometric wordmark that unfolds like an athlete\'s stride. 12 animated logo variants serve different contexts from full-screen reveals to minimal corner bugs. 3D stadium assets in Cinema 4D provide immersive broadcast backgrounds. Every social template auto-animates via Lottie.',
    keyFeatures: ['12 animated logo variants', 'Broadcast-ready lower thirds', '3D stadium environments', 'Auto-animating social templates', 'Speed-optimized Lottie exports', 'Sound-synced motion guidelines'],
    designDirection: 'Athletic energy. Sharp angles, high contrast, and explosive motion. Colors are bold primaries — red, white, black — that pop on any screen size at any speed.',
    outcome: 'Social engagement increased by 190%. Broadcast identity rated #1 in viewer recognition surveys. The motion system reduced content production time by 50%.',
    fullStory: 'Kinetic taught us that brands are no longer static marks on a page — they are living, moving systems. Every pixel was designed in motion first, then derived backward to static.',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-bd45ba22fc82?auto=format&fit=crop&q=80&w=2670',
    galleryImages: ['https://images.unsplash.com/photo-1471295253337-3ceaaedca402?auto=format&fit=crop&q=80&w=2668', 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&q=80&w=2690'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['Logo Animation Sequencer', 'Lower Third Generator', '3D Environment Previewer', 'Color Contrast Checker', 'Motion Timing Editor', 'Social Post Preview Grid'],
    systemDiagram: 'https://images.unsplash.com/photo-1471295253337-3ceaaedca402?auto=format&fit=crop&q=80&w=2668',
    systemDiagramCaption: 'After Effects comps → Cinema 4D renders → Lottie exports → Figma templates → Broadcast delivery pipeline',
    testimonial: { quote: 'Our brand finally matches the energy of the sports we cover. Viewer recognition jumped overnight.', author: 'Marcus Chen', role: 'CEO, Kinetic Sports Media' },
    impact: '190% social engagement, #1 broadcast recognition, 50% faster content production.',
    relatedProjectIds: ['4', '9'], url: 'https://kinetic.qoarc.com',
    metaTitle: 'Kinetic — Motion Branding Case Study | QoArc',
    metaDescription: 'How QoArc created a motion-first brand identity for Kinetic Sports Media, boosting social engagement by 190%.',
    ogImage: 'https://images.unsplash.com/photo-1461896836934-bd45ba22fc82?auto=format&fit=crop&q=80&w=2670',
    isFeatured: false, isVisibleOnHome: true, status: 'published', order: 14
  },
  {
    id: '15',
    name: 'Forge — Developer Portal',
    client: 'Forge Platform Inc.',
    slug: 'forge-developer-portal',
    description: 'An API-first developer portal with interactive documentation, sandbox environments, and usage analytics for a B2B SaaS platform.',
    category: 'Web',
    industry: 'Developer Tools & B2B',
    services: ['Developer Experience Design', 'Full-Stack Development', 'Technical Writing', 'API Design'],
    timeline: '4 Months',
    year: '2023',
    techStack: ['Next.js', 'MDX', 'Swagger/OpenAPI', 'Node.js', 'Redis', 'Docker', 'Stripe'],
    heroImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=2672',
    intro: 'Documentation so good, developers integrate before finishing their coffee.',
    duration: '4 Months',
    scope: 'Interactive API docs, sandbox environment, usage dashboard, billing integration.',
    platform: 'Web',
    deliverables: ['Interactive API Docs', 'Sandbox Environment', 'Usage Dashboard', 'Billing Portal', 'SDK Generator'],
    teamRole: 'DX Engineering Lead',
    challenge: 'Forge\'s API documentation was a static PDF. Developers averaged 14 days to first integration. Support tickets about documentation outnumbered product bugs 3:1.',
    goal: 'Build a developer portal so intuitive that time-to-first-integration drops below 30 minutes.',
    solution: 'We built an interactive portal with MDX-powered docs, live code examples that execute in sandboxed environments, auto-generated SDKs for 6 languages, and real-time usage dashboards with Stripe-integrated billing.',
    keyFeatures: ['Interactive API explorer', 'Live code sandbox per endpoint', 'Auto-generated SDKs (6 languages)', 'Real-time usage analytics', 'Stripe metered billing', 'Versioned documentation'],
    designDirection: 'Developer-centric. Monospace typography, syntax-highlighted everything, terminal-inspired UI. Dark mode only — because developers deserve it.',
    outcome: 'Time to first integration: 22 minutes (from 14 days). Documentation support tickets dropped by 89%. Developer NPS score: 78.',
    fullStory: 'Forge taught us that documentation IS the product for APIs. We treated every page like a product feature, not an afterthought.',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=2672',
    galleryImages: ['https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2670', 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=2670'],
    mobileMockups: [], desktopMockups: [], videoUrl: '',
    uiComponents: ['API Endpoint Explorer', 'Code Sandbox Terminal', 'SDK Language Selector', 'Usage Sparkline Chart', 'Rate Limit Progress Bar', 'Changelog Timeline'],
    systemDiagram: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=2670',
    systemDiagramCaption: 'MDX docs → OpenAPI spec → Sandbox Docker containers → Usage Redis counters → Stripe metered billing',
    testimonial: { quote: 'I integrated Forge in 18 minutes. Best developer experience I have encountered.', author: 'Dev Sarah K.', role: 'Senior Engineer, Integration Partner' },
    impact: '22-min integration time (from 14 days), 89% fewer doc tickets, NPS 78.',
    relatedProjectIds: ['10', '13'], url: 'https://forge.qoarc.com',
    metaTitle: 'Forge — Developer Portal Case Study | QoArc',
    metaDescription: 'How QoArc built Forge, a developer portal that reduced time-to-first-integration from 14 days to 22 minutes.',
    ogImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=2672',
    isFeatured: false, isVisibleOnHome: true, status: 'published', order: 15
  }
];
